import { atividadeStyles, Container, Form, H1, input, inputButton, Label, radioStyles } from '@/styles/Home.css'
import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'
import { UserActivityAcceptedValues } from '@entities/User/UserActivityAcceptedValues'
import { TypeUserActivityAcceptedValues } from '@/entities/User/TypeUserActivityAcceptedValues'
import { User } from '@/entities/User/User'
export let data = {
	basal:0,
}
export default function Home() {
	const [atividadeDesc, setAtividadeDesc] = useState(UserActivityAcceptedValues['1.2'])
	const [uuser, setUuser] = useState(User)
	function atividadesDescs(valor:TypeUserActivityAcceptedValues){
		return UserActivityAcceptedValues[valor]
	}

	const handleChange = (value: { target: { name: string; value: any } })=>{
		let nome = value.target.name
		let valor = value.target.value
		setUuser((prevValue) => ({
			...prevValue,
			[nome]: valor
		}))
		if(nome === 'activity'){
			setAtividadeDesc(atividadesDescs(valor))
		}
	}
	const handleClick = ()=>{
		localStorage.setItem('user', JSON.stringify(uuser))
	}
	console.log(uuser)
	return (
		<>
			<Head>
				<title>Caloric App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className={H1}>
				<b>Calculadora</b>
				<b>Calorica</b>
			</h1>
			<form className={Form} action="#">
				<div className={Container}>
					<label className={Label} htmlFor="weight">Peso</label>
					<input name='weight' type="number" className={input} onChange={handleChange} />
				</div>
				<div className={Container}>
					<label className={Label} htmlFor="height">Altura</label>
					<input name='height' type="number" className={input} onChange={handleChange} />
				</div>
				<div className={Container}>
					<label className={Label} htmlFor="objective">Objetivo</label>
					<select className={input} onChange={handleChange} name="objective" id="objective">
						<option value="perda">Perda de Peso</option>
						<option value="ganho">Ganho de Peso</option>
						<option value="manter">Manter o Peso</option>
					</select>
				</div>
				<div className={Container}>
					<label className={Label} htmlFor="activity">Atividade</label>
					<select className={input} onChange={handleChange} name="activity">
						<option value={1.2}>Sedentario</option>
						<option value={1.375}>Leve</option>
						<option value={1.55}>Moderada</option>
						<option value={1.725}>Alta</option>
						<option value={1.9}>Extremo</option>
					</select>
					<p className={atividadeStyles}>{atividadeDesc}</p>
				</div>
				<div className={Container}>
					<label className={Label} htmlFor="age">Idade</label>
					<input name='age' type="number" className={input} onChange={handleChange} />
				</div>
				<div className={Container}>
					<label htmlFor="gender" className={Label}>Sexo</label>
					<div style={{padding: 5}}>
						<input className={radioStyles} type="radio" name="gender" id="masculino" value={'masculino'} onChange={handleChange} />
						<label htmlFor="masculino">Masculino</label>
					</div>
					<div style={{padding: 5}}>
						<input className={radioStyles} type="radio" name="gender" id="feminino" value={'feminino'} onChange={handleChange} />
						<label htmlFor="feminino">Feminino</label>
					</div>
				</div>
				<div className={Container}>
					<Link style={{textDecoration: 'none'}} href='/resultado'>
						<input type="button" value="Calcular" className={inputButton} onClick={handleClick} />
					</Link>
				</div>
			</form>

		</>
	)
}
