import { atividadeStyles, Container, Form, H1, input, inputButton, Label, radioStyles } from '@/styles/Home.css'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState, useRef, InputHTMLAttributes, ReactElement, ReactPropTypes } from 'react'
import { UserActivityAcceptedValues } from '@entities/User/UserActivityAcceptedValues'
import { TypeUserActivityAcceptedValues } from '@/entities/User/TypeUserActivityAcceptedValues'
import { User } from '@/entities/User/User'
import { InputRange } from '@/components/InputRange/InputRange'
import { darkTheme, lightTheme } from '@/styles/themes.css'
export default function Home() {
	const [mode, setMode] = useState<Boolean>()
	const [user] = useState(new User())
	const [valueLeft, setValueLeft] = useState(100)
	const [atividadeDesc, atividadeDescChange] = useState('Pouco ou nenhum exercício')
	const handleModeChange = ()=>{
		console.log('handleModeChange chamado...')
		if(mode === true){
			setMode(false)
			window.localStorage.setItem('darkMode', String(mode))
			verifyMode()
		}else{
			setMode(true)
			window.localStorage.setItem('darkMode', String(mode))
			verifyMode()
		}
	}
	const verifyMode = ()=>{
		console.log('verifyMode chamado...')
		if(mode === true){
			document.body.classList.remove(lightTheme)
			document.body.classList.add(darkTheme)
			window.localStorage.setItem('darkMode', String(mode))
			return
		}else{
			document.body.classList.remove(darkTheme)
			document.body.classList.add(lightTheme)
			window.localStorage.setItem('darkMode', String(mode))
			return
		}
	}
	let firstRender = false
	useEffect(()=>{
		if(!firstRender){
			if(window.localStorage.getItem('darkMode') === 'undefined' || undefined){
				setMode(false)
				window.localStorage.setItem('darkMode', String(mode))
			}else{
				window.localStorage.getItem('darkMode') === 'false' ? setMode(false) : setMode(true)
				console.log(mode)
			}
		}
		console.log('useEffect chamado...')
		atividadeDescChange(UserActivityAcceptedValues[user.activity as TypeUserActivityAcceptedValues])
		if (firstElementRef.current) {
			firstElementRef.current.focus()
		}
		return ()=> {firstRender = true}
	},[])

	const handleChange = (value:{target:{name: string, value:any}})=>{
		const _name= value.target.name
		const _value = value.target.value
		if(_name === 'activity'){
			user.setActivity(_value)
			atividadeDescChange(UserActivityAcceptedValues[user.activity as TypeUserActivityAcceptedValues])
			return
		}
		//@ts-ignore
		user[_name as keyof User] = _value
		console.log(user)
	}
	const handleClick = ()=>{
		localStorage.setItem('user', JSON.stringify(user))
	}
	const firstElementRef = useRef<HTMLInputElement>(null)
	const lastElementRef = useRef<HTMLInputElement>(null)

	const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
		if (e.key === 'Tab' && e.shiftKey) {
		  // shift + tab
		  if (document.activeElement === firstElementRef.current) {
		    e.preventDefault()
		    lastElementRef.current?.focus()
		  }
		} else if (e.key === 'Tab') {
		  // tab
		  if (document.activeElement === lastElementRef.current) {
		    e.preventDefault()
		    firstElementRef.current?.focus()
		  }
		}
	}

	return (
		<>
			<Head>
				<title>Caloric App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				{
				}
			</Head>
			<h1 className={H1} tabIndex={-1}>
				<b>Calculadora</b>
				<b>Calorica</b>
			</h1>
			<input type="button" onClick={()=>handleModeChange} value="DarkMode"/>
			<form className={Form} action="#" >
				<div className={Container}>
					<label className={Label} htmlFor="weight">Peso</label>
					<input ref={firstElementRef} onKeyDown={handleKeyDown} id='weight' name='weight' type="number" className={input} onChange={handleChange} tabIndex={1} autoFocus={true} />
				</div>
				<div className={Container}>
					<label className={Label} htmlFor="height">Altura</label>
					<input onKeyDown={handleKeyDown} name='height' type="number" className={input} onChange={handleChange} tabIndex={2}/>
				</div>
				<div className={Container}>
					<label className={Label} htmlFor="objective">Objetivo</label>
					<select className={input} name="objective" id="objective" onChange={handleChange} tabIndex={3}>
						<option value="perda">Perda de Peso</option>
						<option value="ganho">Ganho de Peso</option>
						<option value="manter">Manter o Peso</option>
					</select>
				</div>
				<div className={Container}>
					<label className={Label} htmlFor="activity">Atividade</label>
					<select className={input} name="activity" onChange={handleChange} tabIndex={4}>
						<option value={1.2}>Sedentario</option>
						<option value={1.375}>Leve</option>
						<option value={1.55}>Moderada</option>
						<option value={1.725}>Alta</option>
						<option value={1.9}>Extremo</option>
					</select>
					<p className={atividadeStyles}>{atividadeDesc}</p>
				</div>
				<div className={Container}>
					<label className={Label} htmlFor="age">Idade</label>
					<input placeholder='Digite a sua idade' name='age' type="number" className={input} onChange={handleChange} tabIndex={5}/>
				</div>
				<div className={Container}>
					<label htmlFor="gender" className={Label}>Sexo</label>
					<div style={{padding: 5}}>
						<input className={radioStyles} type="radio" name="gender" id="masculino" value={'masculino'} onChange={handleChange} tabIndex={6}/>
						<label htmlFor="masculino">Masculino</label>
					</div>
					<div style={{padding: 5}}>
						<input className={radioStyles} type="radio" name="gender" id="feminino" value={'feminino'} onChange={handleChange} tabIndex={7}/>
						<label htmlFor="feminino">Feminino</label>
					</div>
				</div>
				<InputRange max={100} name='protein' label='Protein'/>
				<InputRange max={50} name='carboidrato' label='Carboidrato'/>
				<InputRange max={30} name='gordura' label='Gordura'/>
				<div className={Container}>
					<Link style={{textDecoration: 'none'}} href='/resultado' tabIndex={-1}>
						<input ref={lastElementRef} onKeyDown={handleKeyDown} id='buttonForm' type="button" value="Calcular" className={inputButton} onClick={handleClick} tabIndex={8} />
					</Link>
				</div>

			</form>

		</>
	)
}
