import { H1 } from '@styles/Home.css'
import Head from 'next/head'
import Link from 'next/link'
import { data } from '..'
export default function Resultado(){
	return(
		<>
			<Head>
				<title>Resultado - Caloric App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Link style={{textDecoration: 'none', color:'purple', fontSize: '64px', padding:'20px'}} href={'/'}> {'<'} </Link>
			<h1 className={H1}>
				<b>Calculadora</b>
				<b>Calorica</b>
			</h1>
			<h2>Gasto Calórico : {data.basal}</h2>
		</>
	)
}